<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Lenovo-PC" name="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents" tests="11" failures="0" timestamp="2020-05-05T16:34:50 IST" time="481.245" errors="3">
  <testcase name="RechargeIntentOneCheckAfterLogin" time="41.148" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents"/>
  <system-out/>
  <testcase name="RechargeIntentTwoCheckAfterLogin" time="41.181" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents"/>
  <system-out/>
  <testcase name="RechargeIntentThreeCheckAfterLogin" time="40.643" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents"/>
  <system-out/>
  <testcase name="RechargeIntentFourCheckAfterLogin" time="47.737" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents"/>
  <system-out/>
  <testcase name="RechargeIntentFiveCheckAfterLogin" time="40.351" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents"/>
  <system-out/>
  <testcase name="RechargeIntentSixCheckAfterLogin" time="48.991" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents">
    <error type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:29)
at wrappers.GenericWrappers.verifyTextByXpath(GenericWrappers.java:475)
at pages.RechargePage.verifyValidSelectAccountText(RechargePage.java:80)
at testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents.RechargeIntentSixCheckAfterLogin(TC05VerifyRechargeModuleUsingRechargeSupportedIntents.java:121)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- RechargeIntentSixCheckAfterLogin -->
  <system-out/>
  <testcase name="RechargeIntentSevenCheckAfterLogin" time="40.883" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents"/>
  <system-out/>
  <testcase name="RechargeIntentEightCheckAfterLogin" time="40.121" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents"/>
  <system-out/>
  <testcase name="RechargeIntentNineCheckAfterLogin" time="51.350" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents">
    <error type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:29)
at wrappers.GenericWrappers.verifyTextByXpath(GenericWrappers.java:475)
at pages.RechargePage.verifyValidSelectAccountText(RechargePage.java:80)
at testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents.RechargeIntentNineCheckAfterLogin(TC05VerifyRechargeModuleUsingRechargeSupportedIntents.java:169)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- RechargeIntentNineCheckAfterLogin -->
  <system-out/>
  <testcase name="RechargeIntentTenCheckAfterLogin" time="41.442" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents"/>
  <system-out/>
  <testcase name="RechargeIntentElevenCheckAfterLogin" time="47.398" classname="testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents">
    <error type="java.lang.RuntimeException" message="FAILED">
      <![CDATA[java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:29)
at wrappers.GenericWrappers.verifyTextByXpath(GenericWrappers.java:475)
at pages.RechargePage.verifyValidSelectAccountText(RechargePage.java:80)
at testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents.RechargeIntentElevenCheckAfterLogin(TC05VerifyRechargeModuleUsingRechargeSupportedIntents.java:201)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- RechargeIntentElevenCheckAfterLogin -->
  <system-out/>
</testsuite> <!-- testcases.recharge.TC05VerifyRechargeModuleUsingRechargeSupportedIntents -->
